DemoPayPal/DemoPayPal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoPayPal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modifique esta plantilla para poner en marcha su aplicación ASP.NET MVC.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Página de descripción de la aplicación.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Página de contacto.";

            return View();
        }
    }
}

DemoPayPal/DemoPayPal/Controllers/PayPalController.cs
using System;
using System.Configuration;
using System.Web.Mvc;
using DemoPayPal.Models;

namespace DemoPayPal.Controllers
{
    public class PayPalController : Controller
    {
        public ActionResult RedireccionarDesdePayPal()
        {
            return View();
        }

        public ActionResult CancelarDesdePayPal()
        {
            return View();
        }

        public ActionResult NotificarDesdePayPal()
        {
            return View();
        }
        
        public ActionResult RealizarCompra(string producto, string totalPrecio)
        {
            bool useSandbox = Convert.ToBoolean(ConfigurationManager.AppSettings["IsSandbox"]);
            var paypal = new PayPalModel(useSandbox);

            paypal.item_name = producto;
            paypal.amount = totalPrecio;
            return View(paypal);
        }
    }
}

DemoPayPal/DemoPayPal/Views/Home/About.cshtml
@{
    ViewBag.Title = "Acerca de";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use esta área para proporcionar información adicional.
    </p>

    <p>
        Use esta área para proporcionar información adicional.
    </p>

    <p>
        Use esta área para proporcionar información adicional.
    </p>
</article>

<aside>
    <h3>Al lado del título</h3>
    <p>
        Use esta área para proporcionar información adicional.
    </p>
    <ul>
        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
        <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
    </ul>
</aside>

DemoPayPal/DemoPayPal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contacto";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Teléfono</h3>
    </header>
    <p>
        <span class="label">Principal:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">Fuera del horario laboral:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Correo electrónico</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Dirección</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

DemoPayPal/DemoPayPal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Página principal";
}

@using(Html.BeginForm("RealizarCompra","PayPal"))
{
    <div>
        <table>
            <tr>
                <td>
                    Producto :
                </td>
                <td>
                    <input type="text" name="producto" value="Matícula Curso Android" readonly="readonly"/>
                </td>
            </tr>
            <tr>
                <td>
                    Precio :
                </td>
                <td>
                    <input type="text" name="totalPrecio" value="300" readonly="readonly"/>
                </td>
            </tr>
            <tr>
                <td>
                </td>
                <td>
                    <input type="submit" name="btnComprar" value="Pagar con PayPal"/>
                </td>
            </tr>
        </table>
    </div>
}